# Generated by Django 4.2.9 on 2024-01-31 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_alter_review_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=0, max_length=12, unique=True, verbose_name='Купон')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='Размер скидки')),
                ('available', models.BooleanField(default=True, verbose_name='Активность')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('is_mass', models.BooleanField(default=False)),
            ],
        ),
    ]
