# Generated by Django 4.2.9 on 2024-01-31 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_rating'),
        ('recommend', '0003_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.product',),
        ),
    ]
