# Generated by Django 4.2.9 on 2024-02-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_order_coupon'),
        ('recommend', '0004_couponproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='CouponProxy',
        ),
    ]
