# Generated by Django 4.2.9 on 2024-01-31 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_coupon'),
        ('payment', '0006_order_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='recommend.coupon'),
            preserve_default=False,
        ),
    ]
